name: Function Request Report
description: Function request report
title: "[Feature/Function]: "
labels: ["Type: Feature/Function","Status: To Do"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        개발 요구사항 레포트!
  - type: dropdown
    id: Domain
    attributes:
      label: Domain
      description: 어떤 Domain에 관련된 Issue입니까?
      options:
        - User
        - Board
        - ETC
    validations:
      required: true
  - type: textarea
    id: what-need
    attributes:
      label: Function
      description: Function
      placeholder: Function
      value: "Fucntion"
    validations:
      required: true
  - type: textarea
    id: consideration
    attributes:
      label: Consideration
      description: Consideration
  - type: checkboxes
    id: priority
    attributes:
      label: Priority Label Setting
      description: Priority Label?
      options:
        - label: Priority Label.
          required: true
  - type: checkboxes
    id: projects
    attributes:
      label: Projects Card
      description: Project Card?
      options:
        - label: Yes Create
          required: true
